export const data = [
    {
      id: 1,
      first_name: 'Wilmette',
      last_name: 'Maasz',
      email: 'wmaasz0@jalbum.net',
      phone: '130-309-6439',
    },
    {
      id: 2,
      first_name: 'Morry',
      last_name: 'Heater',
      email: 'mheater1@yale.edu',
      phone: '814-809-2958',
    },
    {
      id: 3,
      first_name: 'Laverne',
      last_name: 'MacMorland',
      email: 'lmacmorland2@webnode.com',
      phone: '271-342-7249',
    },
    {
      id: 4,
      first_name: 'Cindee',
      last_name: 'De Freitas',
      email: 'cdefreitas3@privacy.gov.au',
      phone: '617-624-6967',
    },
    {
      id: 5,
      first_name: 'Carole',
      last_name: 'Reffe',
      email: 'creffe4@nih.gov',
      phone: '738-966-3137',
    },
    {
      id: 6,
      first_name: 'Ansel',
      last_name: 'Iwanicki',
      email: 'aiwanicki5@pagesperso-orange.fr',
      phone: '716-371-2467',
    },
    {
      id: 7,
      first_name: 'Herold',
      last_name: 'Mungham',
      email: 'hmungham6@goodreads.com',
      phone: '659-298-5396',
    },
    {
      id: 8,
      first_name: 'Sibeal',
      last_name: 'Andreacci',
      email: 'sandreacci7@bloomberg.com',
      phone: '508-876-5450',
    },
    {
      id: 9,
      first_name: 'Eustacia',
      last_name: 'Matteuzzi',
      email: 'ematteuzzi8@rakuten.co.jp',
      phone: '953-375-3684',
    },
    {
      id: 10,
      first_name: 'Tiebold',
      last_name: 'Powe',
      email: 'tpowe9@dmoz.org',
      phone: '574-154-1045',
    }
]